name: email-cons-agent
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - python=3.13.11
  - langchain=1.2.15
  - langgraph=1.1.6
  - langchain-mistralai=1.1.1
  - langchain-google-genai=4.2.1
  - langfuse-python=3.14.4
  - python-dotenv=1.2.1
  - pip
  - pip:
    - playwright==1.58.0